import { api } from './client';
import { Account, AdminAnalytics, Card, CreditEstimate, Deposit, DepositEstimate, FraudCheck, FraudTransaction, Loan, MonthlyAnalytics, Transaction, User, DonationCampaign } from '../types/bank';
export const bankApi = {
  accounts: () => api.get<Account[]>('/api/accounts').then(r => r.data),
  account: (id: string | number) => api.get<Account>(`/api/accounts/${id}`).then(r => r.data),
  createAccount: (data: { type: string; currency: string; productName?: string; packageName?: string }) => api.post<Account>('/api/accounts', data).then(r => r.data),
  topUp: (id: number, amount: number) => api.post<Account>(`/api/accounts/${id}/top-up`, { amount }).then(r => r.data),
  withdraw: (id: number, amount: number) => api.post<Account>(`/api/accounts/${id}/withdraw`, { amount }).then(r => r.data),
  transactions: () => api.get<Transaction[]>('/api/transactions').then(r => r.data),
  accountTransactions: (id: string | number) => api.get<Transaction[]>(`/api/transactions/accounts/${id}`).then(r => r.data),
  transfer: (data: { fromAccountId: number; toIban: string; amount: number; description?: string; operationId: string }) => api.post<Transaction>('/api/transactions/transfer', data).then(r => r.data),
  cards: () => api.get<Card[]>('/api/cards').then(r => r.data),
  createCard: (data: { accountId: number; tier?: string }) => api.post<Card>('/api/cards', data).then(r => r.data),
  setCard: (id: number, action: 'block'|'unblock') => api.patch<Card>(`/api/cards/${id}/${action}`).then(r => r.data),
  profile: () => api.get<User>('/api/profile').then(r => r.data),
  updateProfile: (data: Partial<User> & Pick<User, 'firstName'|'lastName'|'email'>) => api.patch<User>('/api/profile', data).then(r => r.data),
  loans: () => api.get<Loan[]>('/api/loans').then(r => r.data),
  creditEstimate: (amount: number, months: number) => api.get<CreditEstimate>(`/api/credit/estimate?amount=${amount}&months=${months}`).then(r => r.data),
  applyLoan: (data: { amount: number; termMonths: number; purpose?: string }) => api.post<Loan>('/api/loans/applications', data).then(r => r.data),
  deposits: () => api.get<Deposit[]>('/api/deposits').then(r => r.data),
  depositEstimate: (amount: number, termMonths: number) => api.get<DepositEstimate>(`/api/deposits/estimate?amount=${amount}&termMonths=${termMonths}`).then(r => r.data),
  applyDeposit: (data: { sourceAccountId: number; amount: number; termMonths: number; productName?: string; capitalization?: boolean; earlyWithdrawal?: boolean }) => api.post<Deposit>('/api/deposits/applications', data).then(r => r.data),
  fraudCheck: (data: { message: string; amount: number; currency: string }) => api.post<FraudCheck>('/api/fraud/analyze', data).then(r => r.data),
  fraudTransactions: () => api.get<FraudTransaction[]>('/api/fraud/transactions').then(r => r.data),
  reviewFraud: (id: number, status: 'SAFE'|'SUSPICIOUS', note?: string) => api.post<FraudTransaction>(`/api/fraud/transactions/${id}/review`, { status, note }).then(r => r.data),
  adminFraudTransactions: () => api.get<FraudTransaction[]>('/api/admin/fraud/transactions').then(r => r.data),
  adminReviewFraud: (id: number, status: 'SAFE'|'SUSPICIOUS', note?: string) => api.post<FraudTransaction>(`/api/admin/fraud/transactions/${id}/review`, { status, note }).then(r => r.data),
  adminUsers: () => api.get<User[]>('/api/admin/users').then(r => r.data),
  adminAnalytics: () => api.get<AdminAnalytics>('/api/admin/users/analytics').then(r => r.data),
  createAdmin: (data: { firstName: string; lastName: string; email: string; password: string }) => api.post<User>('/api/admin/users/admins', data).then(r => r.data),
  updateRole: (id: number, role: string) => api.patch<User>(`/api/admin/users/${id}/role`, { role }).then(r => r.data),
  analytics: (year: number, month: number) => api.get<MonthlyAnalytics>(`/api/analytics/monthly?year=${year}&month=${month}`).then(r => r.data),
  donationCampaigns: () => api.get<DonationCampaign[]>('/api/donations/campaigns').then(r => r.data),
  donate: (data: { fromAccountId: number; campaignId: number; amount: number; operationId: string; message?: string }) => api.post<Transaction>('/api/donations/send', data).then(r => r.data)
};
